/*
  Phase 2: Dynamic Tables — Medallion Pipeline
  BRONZE: cleanse, deduplicate
  SILVER: feature engineering, 24h stats, PIT joins
  GOLD: OEE metrics
*/

-- ============================================================
-- BRONZE LAYER
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.BRONZE.BRONZE_SENSOR_STREAM
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    READING_ID, ASSET_ID, TS,
    ROUND(VIBRATION_MM_S, 4) AS VIBRATION_MM_S,
    ROUND(TEMP_C, 2)         AS TEMP_C,
    ROUND(RPM, 2)            AS RPM
FROM PDM_OEE_DB.RAW.SENSOR_STREAM
QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID, TS ORDER BY READING_ID) = 1;

CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.BRONZE.BRONZE_ERP_WORKORDER
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    WO_ID, ASSET_ID,
    UPPER(TRIM(TYPE))         AS WO_TYPE,
    OPENED_TS, CLOSED_TS, COST,
    TRIM(TECHNICIAN)          AS TECHNICIAN,
    UPPER(TRIM(FAILURE_CODE)) AS FAILURE_CODE,
    CASE WHEN CLOSED_TS IS NOT NULL THEN 'COMPLETED' ELSE 'OPEN' END AS STATUS,
    CASE WHEN CLOSED_TS IS NOT NULL
         THEN DATEDIFF('hour', OPENED_TS, CLOSED_TS)
    END AS DURATION_HOURS
FROM PDM_OEE_DB.RAW.ERP_WORKORDER
QUALIFY ROW_NUMBER() OVER (PARTITION BY WO_ID ORDER BY OPENED_TS) = 1;

CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.BRONZE.BRONZE_MAINTENANCE_LOG
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    LOG_ID, ASSET_ID, TS,
    TRIM(NOTE_TEXT)      AS NOTE_TEXT,
    TRIM(TECHNICIAN)     AS TECHNICIAN,
    LENGTH(NOTE_TEXT)     AS NOTE_LENGTH
FROM PDM_OEE_DB.RAW.MAINTENANCE_LOG
QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID, TS, TECHNICIAN ORDER BY LOG_ID) = 1;

CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.BRONZE.BRONZE_PRODUCTION_LOG
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    PRODUCTION_ID, ASSET_ID, SHIFT_DATE,
    UPPER(TRIM(SHIFT)) AS SHIFT,
    PLANNED_TIME,
    GREATEST(0, LEAST(RUN_TIME, PLANNED_TIME)) AS RUN_TIME,
    IDEAL_CYCLE_TIME,
    GOOD_UNITS, TOTAL_UNITS
FROM PDM_OEE_DB.RAW.PRODUCTION_LOG
WHERE PLANNED_TIME > 0 AND TOTAL_UNITS >= 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID, SHIFT_DATE, SHIFT ORDER BY PRODUCTION_ID) = 1;

-- ============================================================
-- SILVER LAYER
-- ============================================================

-- Feature engineering with point-in-time work order joins
CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.SILVER.SILVER_SENSOR_ENRICHED
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
WITH timeline AS (
    SELECT
        s.READING_ID, s.ASSET_ID, s.TS,
        s.VIBRATION_MM_S, s.TEMP_C, s.RPM,
        NULL::TIMESTAMP_NTZ AS WO_CLOSED_TS,
        0 AS ROW_ORD
    FROM PDM_OEE_DB.BRONZE.BRONZE_SENSOR_STREAM s
    UNION ALL
    SELECT
        NULL, w.ASSET_ID, w.CLOSED_TS,
        NULL, NULL, NULL,
        w.CLOSED_TS,
        -1
    FROM PDM_OEE_DB.BRONZE.BRONZE_ERP_WORKORDER w
    WHERE w.CLOSED_TS IS NOT NULL
),
with_pit AS (
    SELECT *,
        LAST_VALUE(WO_CLOSED_TS IGNORE NULLS) OVER (
            PARTITION BY ASSET_ID ORDER BY TS, ROW_ORD
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS PIT_LAST_WO_CLOSED
    FROM timeline
),
sensor_only AS (
    SELECT * FROM with_pit WHERE ROW_ORD = 0
)
SELECT
    s.READING_ID, s.ASSET_ID, s.TS,
    a.WIND_FARM, a.TURBINE_ID, a.SUBSYSTEM,
    a.ASSET_CRITICALITY, a.SITE_PRIORITY,
    s.VIBRATION_MM_S, s.TEMP_C, s.RPM,
    AVG(s.VIBRATION_MM_S) OVER (PARTITION BY s.ASSET_ID ORDER BY s.TS ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS VIB_1H_AVG,
    STDDEV(s.VIBRATION_MM_S) OVER (PARTITION BY s.ASSET_ID ORDER BY s.TS ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS VIB_1H_STD,
    AVG(s.TEMP_C) OVER (PARTITION BY s.ASSET_ID ORDER BY s.TS ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS TEMP_1H_AVG,
    STDDEV(s.TEMP_C) OVER (PARTITION BY s.ASSET_ID ORDER BY s.TS ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS TEMP_1H_STD,
    s.RPM - LAG(s.RPM, 1) OVER (PARTITION BY s.ASSET_ID ORDER BY s.TS) AS RPM_DELTA,
    DATEDIFF('hour', s.PIT_LAST_WO_CLOSED, s.TS) AS HOURS_SINCE_LAST_WO
FROM sensor_only s
JOIN PDM_OEE_DB.RAW.ASSET_MASTER a ON s.ASSET_ID = a.ASSET_ID;

-- 24-hour aggregated statistics
CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.SILVER.SILVER_SENSOR_STATS_24H
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
WITH buckets AS (
    SELECT
        s.ASSET_ID,
        a.WIND_FARM, a.TURBINE_ID, a.SUBSYSTEM,
        a.ASSET_CRITICALITY, a.SITE_PRIORITY,
        TIME_SLICE(s.TS, 15, 'MINUTE', 'START') AS BUCKET_TS,
        AVG(s.VIBRATION_MM_S)    AS VIB_BUCKET_AVG,
        STDDEV(s.VIBRATION_MM_S) AS VIB_BUCKET_STD,
        MAX(s.VIBRATION_MM_S)    AS VIB_BUCKET_MAX,
        AVG(s.TEMP_C)            AS TEMP_BUCKET_AVG,
        STDDEV(s.TEMP_C)         AS TEMP_BUCKET_STD,
        MAX(s.TEMP_C)            AS TEMP_BUCKET_MAX,
        AVG(s.RPM)               AS RPM_BUCKET_AVG,
        COUNT(*)                 AS READINGS_IN_BUCKET
    FROM PDM_OEE_DB.BRONZE.BRONZE_SENSOR_STREAM s
    JOIN PDM_OEE_DB.RAW.ASSET_MASTER a ON s.ASSET_ID = a.ASSET_ID
    GROUP BY s.ASSET_ID, a.WIND_FARM, a.TURBINE_ID, a.SUBSYSTEM,
             a.ASSET_CRITICALITY, a.SITE_PRIORITY, BUCKET_TS
)
SELECT
    ASSET_ID, WIND_FARM, TURBINE_ID, SUBSYSTEM,
    ASSET_CRITICALITY, SITE_PRIORITY,
    BUCKET_TS,
    VIB_BUCKET_AVG, VIB_BUCKET_STD, VIB_BUCKET_MAX,
    TEMP_BUCKET_AVG, TEMP_BUCKET_STD, TEMP_BUCKET_MAX,
    RPM_BUCKET_AVG, READINGS_IN_BUCKET,
    AVG(VIB_BUCKET_AVG) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS VIB_24H_AVG,
    STDDEV(VIB_BUCKET_AVG) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS VIB_24H_STD,
    MAX(VIB_BUCKET_MAX) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS VIB_24H_MAX,
    AVG(TEMP_BUCKET_AVG) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS TEMP_24H_AVG,
    STDDEV(TEMP_BUCKET_AVG) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS TEMP_24H_STD,
    MAX(TEMP_BUCKET_MAX) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS ROWS BETWEEN 95 PRECEDING AND CURRENT ROW) AS TEMP_24H_MAX,
    VIB_BUCKET_AVG - LAG(VIB_BUCKET_AVG, 24) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS) AS VIB_6H_DELTA,
    TEMP_BUCKET_AVG - LAG(TEMP_BUCKET_AVG, 24) OVER (PARTITION BY ASSET_ID ORDER BY BUCKET_TS) AS TEMP_6H_DELTA
FROM buckets;

-- Work order enrichment
CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.SILVER.SILVER_WORKORDER_ENRICHED
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    w.WO_ID, w.ASSET_ID,
    a.WIND_FARM, a.TURBINE_ID, a.SUBSYSTEM,
    a.ASSET_CRITICALITY, a.SITE_PRIORITY,
    w.WO_TYPE, w.OPENED_TS, w.CLOSED_TS, w.STATUS, w.DURATION_HOURS,
    w.COST, w.TECHNICIAN, w.FAILURE_CODE,
    COALESCE(m.NOTE_COUNT, 0) AS NOTE_COUNT,
    m.COMBINED_NOTES
FROM PDM_OEE_DB.BRONZE.BRONZE_ERP_WORKORDER w
JOIN PDM_OEE_DB.RAW.ASSET_MASTER a ON w.ASSET_ID = a.ASSET_ID
LEFT JOIN (
    SELECT ml.ASSET_ID, wo.WO_ID,
        COUNT(*)                                                     AS NOTE_COUNT,
        LISTAGG(ml.NOTE_TEXT, ' | ') WITHIN GROUP (ORDER BY ml.TS)  AS COMBINED_NOTES
    FROM PDM_OEE_DB.BRONZE.BRONZE_MAINTENANCE_LOG ml
    JOIN PDM_OEE_DB.BRONZE.BRONZE_ERP_WORKORDER wo
         ON ml.ASSET_ID = wo.ASSET_ID
         AND ml.TS BETWEEN wo.OPENED_TS
             AND COALESCE(wo.CLOSED_TS, DATEADD('day', 365, wo.OPENED_TS))
    GROUP BY ml.ASSET_ID, wo.WO_ID
) m ON w.ASSET_ID = m.ASSET_ID AND w.WO_ID = m.WO_ID;

-- ============================================================
-- GOLD LAYER
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE PDM_OEE_DB.GOLD.GOLD_OEE_METRICS
    TARGET_LAG = '15 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    p.ASSET_ID, a.WIND_FARM, a.TURBINE_ID, a.SUBSYSTEM,
    a.ASSET_CRITICALITY, a.SITE_PRIORITY,
    p.SHIFT_DATE, p.SHIFT,
    p.PLANNED_TIME, p.RUN_TIME, p.IDEAL_CYCLE_TIME,
    p.TOTAL_UNITS, p.GOOD_UNITS,
    p.TOTAL_UNITS - p.GOOD_UNITS AS REJECT_UNITS,
    ROUND(p.RUN_TIME / NULLIF(p.PLANNED_TIME, 0), 4) AS AVAILABILITY,
    ROUND((p.IDEAL_CYCLE_TIME * p.TOTAL_UNITS) / NULLIF(p.RUN_TIME * 60, 0), 4) AS PERFORMANCE,
    ROUND(p.GOOD_UNITS::FLOAT / NULLIF(p.TOTAL_UNITS, 0), 4) AS QUALITY,
    ROUND(
        (p.RUN_TIME / NULLIF(p.PLANNED_TIME, 0)) *
        ((p.IDEAL_CYCLE_TIME * p.TOTAL_UNITS) / NULLIF(p.RUN_TIME * 60, 0)) *
        (p.GOOD_UNITS::FLOAT / NULLIF(p.TOTAL_UNITS, 0))
    , 4) AS OEE
FROM PDM_OEE_DB.BRONZE.BRONZE_PRODUCTION_LOG p
JOIN PDM_OEE_DB.RAW.ASSET_MASTER a ON p.ASSET_ID = a.ASSET_ID;
