/*
  Phase 1: RAW Schema — Base Tables
  Database: PDM_OEE_DB
  Schema: RAW
*/

-- 1a. Create database and schemas
CREATE DATABASE IF NOT EXISTS PDM_OEE_DB;
CREATE SCHEMA IF NOT EXISTS PDM_OEE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS PDM_OEE_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS PDM_OEE_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS PDM_OEE_DB.GOLD;

-- 1b. Sensor telemetry stream (768K readings, 50 assets, 10+1 days)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.SENSOR_STREAM (
    READING_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(12) NOT NULL,
    TS TIMESTAMP_NTZ(9) NOT NULL,
    VIBRATION_MM_S FLOAT,
    TEMP_C FLOAT,
    RPM FLOAT
);

-- 1c. Asset master (50 assets across 3 wind farms)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.ASSET_MASTER (
    ASSET_ID VARCHAR(12) NOT NULL,
    WIND_FARM VARCHAR(30),
    TURBINE_ID VARCHAR(10),
    SUBSYSTEM VARCHAR(20),
    ASSET_CRITICALITY VARCHAR(10),
    SITE_PRIORITY NUMBER(38,0)
);

-- 1d. ERP work orders
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.ERP_WORKORDER (
    WO_ID VARCHAR(20) NOT NULL,
    ASSET_ID VARCHAR(12),
    TYPE VARCHAR(20),
    OPENED_TS TIMESTAMP_NTZ(9),
    CLOSED_TS TIMESTAMP_NTZ(9),
    COST NUMBER(38,0),
    TECHNICIAN VARCHAR(50),
    FAILURE_CODE VARCHAR(200)
);

-- 1e. Maintenance log (technician notes)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.MAINTENANCE_LOG (
    LOG_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(12),
    TS TIMESTAMP_NTZ(9),
    NOTE_TEXT VARCHAR(5000),
    TECHNICIAN VARCHAR(50)
);

-- 1f. Production log (OEE source data)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.PRODUCTION_LOG (
    PRODUCTION_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(12),
    SHIFT_DATE DATE,
    SHIFT VARCHAR(10),
    PLANNED_TIME NUMBER(38,0),
    RUN_TIME NUMBER(38,0),
    IDEAL_CYCLE_TIME FLOAT,
    GOOD_UNITS NUMBER(38,0),
    TOTAL_UNITS NUMBER(38,0)
);

-- 1g. Replay buffer (hourly batch drip for Day 11)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.REPLAY_BUFFER (
    READING_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(12),
    TS TIMESTAMP_NTZ(9),
    VIBRATION_MM_S FLOAT,
    TEMP_C FLOAT,
    RPM FLOAT,
    REPLAY_HOUR NUMBER(38,0)
);

-- 1h. Agent action log (audit trail)
CREATE OR REPLACE TABLE PDM_OEE_DB.RAW.AGENT_ACTION_LOG (
    ACTION_ID VARCHAR(36) DEFAULT UUID_STRING(),
    ACTION_TYPE VARCHAR(30),
    ASSET_ID VARCHAR(12),
    CONFIDENCE FLOAT,
    DETAILS VARCHAR(1000),
    CREATED_BY VARCHAR(50) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- 1i. Notification config
CREATE OR REPLACE TABLE PDM_OEE_DB.GOLD.NOTIFICATION_CONFIG (
    CONFIG_ID NUMBER(38,0) NOT NULL,
    REPORT_TYPE VARCHAR(30) NOT NULL,
    RECIPIENT VARCHAR(100) NOT NULL,
    THRESHOLD FLOAT DEFAULT 0.85
);

-- Insert notification recipient (replace with your email)
INSERT INTO PDM_OEE_DB.GOLD.NOTIFICATION_CONFIG (CONFIG_ID, REPORT_TYPE, RECIPIENT)
VALUES (1, 'CRITICAL_ALERT', 'recipient@example.com');
